services:
  postgres-db:
    image: postgres
    restart: always
    container_name: postgres-db
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=evora_event_db
    networks:
      - evora-network

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    container_name: pg-admin
    ports:
      - '15432:80'
    depends_on:
      - postgres-db
    environment:
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    networks:
      - evora-network

  mongo-db:
    image: mongo:latest
    restart: always
    container_name: mongo-db
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: evora_user_db
    networks:
      - evora-network

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - evora-network

networks:
  evora-network:
    driver: bridge