spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: user-service-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/v1/events/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}