jwt:
  secret: ${JWT_KEY}
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: user-service-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter
        - id: event-service-1
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/v1/events/**
          filters:
            - AuthenticationFilter
        - id: event-service-2
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/v1/tickets/**
          filters:
            - AuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}