jwt:
  secret: ${JWT_KEY}
server:
  port: 8082
spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      authentication-database: admin
      username: ${DB_USER:admin}
      password: ${DB_PASSWORD:password}
      database: evora_user_db
      port: ${DB_PORT:27018}
      host: ${DB_HOST:localhost}
      auto-index-creation: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}