api:
  key: ${API_KEY}

server:
  port: 8083

spring:
  application:
    name:
      EVENT-SERVICE
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/evora_event_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${DB_URL:jdbc:postgresql://localhost:5432/evora_event_db}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}